taskler/main/routes.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__)


@main.route('/')
def home():
    return render_template('main/home.html')

taskler/projects/routes.py
from flask import render_template, Blueprint, flash, redirect, url_for, request
from taskler.models import Project, Task, Subtype
from taskler.db import db_session
from taskler.projects.forms import ProjectForm
from taskler.tasks.forms import TaskForm
from taskler.utils import local_to_utc


projects = Blueprint('projects', __name__)


@projects.route('/project/new', methods=['GET', 'POST'])
def new_project():
    form = ProjectForm()
    if form.validate_on_submit():
        my_project = Project(title=form.title.data,
                             description=form.description.data,
                             start_date=local_to_utc(form.start_date.data),
                             end_date=local_to_utc(form.end_date.data),
                             status=form.status.data)
        db_session.add(my_project)
        db_session.commit()
        flash('Your project has been created!', 'success')
        return redirect(url_for('projects.project', project_id=my_project.id))
    return render_template('projects/create_project.html', form=form)


@projects.route('/project/<int:project_id>/update', methods=['GET', 'POST'])
def update_project(project_id):
    form = ProjectForm()
    my_project = db_session.query(Project).filter(Project.id == project_id).first()
    if form.validate_on_submit():
        my_project.start_date = form.start_date.data
        my_project.end_date = form.end_date.data
        my_project.title = form.title.data
        my_project.description = form.description.data
        db_session.add(my_project)
        db_session.commit()
        return redirect(url_for('projects.project', project_id=my_project.id))
    elif request.method == 'GET':
        form.start_date.data = my_project.start_date
        form.end_date.data = my_project.end_date
        form.title.data = my_project.title
        form.description.data = my_project.description
    return render_template('projects/update_project.html', form=form)


@projects.route('/project/<int:project_id>/new-task', methods=['GET', 'POST'])
def new_project_task(project_id):
    form = TaskForm()
    my_project = db_session.query(Project).get(project_id)
    if form.validate_on_submit():
        my_task = Task(title=form.title.data,
                       description=form.description.data,
                       date_due=local_to_utc(form.date_due.data),
                       start_date=local_to_utc(form.start_date.data),
                       project_id=my_project.id,
                       status=form.status.data)
        task_subtypes = []
        for subtype in form.subtypes.data:
            task_subtypes.append(db_session.query(Subtype).filter(Subtype.type == subtype).first())
        my_task.subtypes = task_subtypes
        db_session.add(my_task)
        db_session.commit()
        flash('Your task has been created!', 'success')
        return redirect(url_for('projects.project', project_id=my_project.id))
    return render_template('projects/create_project_task.html', form=form, project=my_project)


@projects.route('/project/<int:project_id>')
def project(project_id):
    my_project = db_session.query(Project).filter(Project.id == project_id).first()
    project_tasks = my_project.tasks
    return render_template('projects/project.html', project=my_project, tasks=project_tasks)


@projects.route('/project/<int:project_id>/delete', methods=['POST'])
def delete_project(project_id):
    my_project = db_session.query(Project).get(project_id)
    if my_project:
        db_session.delete(my_project)
        db_session.commit()
        flash('Your project has been deleted!', 'success')
        return redirect(url_for('main.home'))
    flash('Project deletion failed!', 'danger')
    return redirect(url_for('main.home'))

taskler/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
  <!-- Custom CSS -->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">

  <title>Tasklr: A Lr for Tasks</title>
</head>
<body>
  <div class="wrapper">
    <nav id="sidebar">
      <div class="sidebar-header">
        <h3>Tasklr Navigator</h3>
      </div>
      <ul class="list-unstyled-components">
        <li>
          <a href="{{ url_for('main.home') }}">Home</a>
        </li>
        <li>
          <a href="#projectNav" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Projects</a>
          <ul class="collapse-list-unstyled" id="projectNav">
            {% for project in projects %}
              <li>
                <a href="{{ url_for('projects.project', project_id=project.id) }}">{{ project.title }}</a>
              </li>
            {% endfor %}
          </ul>
        </li>
        <li>
          <a href="{{ url_for('projects.new_project') }}">+ New Project</a>
        </li>
        <li>
          <a href="{{ url_for('subtypes.all_subtypes') }}">+ Create New Subtypes</a>
        </li>
      </ul>
    </nav>
    <div id="content" class="container">
      <div>
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>
      {% block content %}
      {% endblock %}
    </div>
  </div>

  <script src="{{ url_for('static', filename='main.js') }}"></script>
  {{ moment.include_jquery() }}
  {{ moment.include_moment() }}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>