taskler/projects/routes.py
from flask import render_template, Blueprint, flash, redirect, url_for, request
from taskler.models import Project, Task, Subtype
from taskler.db import db_session
from taskler.projects.forms import ProjectForm
from taskler.tasks.forms import TaskForm
from taskler.utils import local_to_utc


projects = Blueprint('projects', __name__)


@projects.route('/project/new', methods=['GET', 'POST'])
def new_project():
    form = ProjectForm()
    if form.validate_on_submit():
        my_project = Project(title=form.title.data,
                             description=form.description.data,
                             start_date=local_to_utc(form.start_date.data),
                             end_date=local_to_utc(form.end_date.data),
                             status=form.status.data)
        db_session.add(my_project)
        db_session.commit()
        flash('Your project has been created!', 'success')
        return redirect(url_for('projects.project', project_id=my_project.id))
    return render_template('projects/create_project.html', form=form)


@projects.route('/project/<int:project_id>/update', methods=['GET', 'POST'])
def update_project(project_id):
    form = ProjectForm()
    my_project = db_session.query(Project).filter(Project.id == project_id).first()
    if form.validate_on_submit():
        my_project.start_date = form.start_date.data
        my_project.end_date = form.end_date.data
        my_project.title = form.title.data
        my_project.description = form.description.data
        db_session.add(my_project)
        db_session.commit()
        return redirect(url_for('projects.project', project_id=my_project.id))
    elif request.method == 'GET':
        form.start_date.data = my_project.start_date
        form.end_date.data = my_project.end_date
        form.title.data = my_project.title
        form.description.data = my_project.description
    return render_template('projects/update_project.html', form=form)


@projects.route('/project/<int:project_id>/new-task', methods=['GET', 'POST'])
def new_project_task(project_id):
    form = TaskForm()
    my_project = db_session.query(Project).get(project_id)
    if form.validate_on_submit():
        my_task = Task(title=form.title.data,
                       description=form.description.data,
                       date_due=local_to_utc(form.date_due.data),
                       start_date=local_to_utc(form.start_date.data),
                       project_id=my_project.id,
                       status=form.status.data)
        task_subtypes = []
        for subtype in form.subtypes.data:
            task_subtypes.append(db_session.query(Subtype).filter(Subtype.type == subtype).first())
        my_task.subtypes = task_subtypes
        db_session.add(my_task)
        db_session.commit()
        flash('Your task has been created!', 'success')
        return redirect(url_for('projects.project', project_id=my_project.id))
    return render_template('projects/create_project_task.html', form=form, project=my_project)


@projects.route('/project/<int:project_id>')
def project(project_id):
    my_project = db_session.query(Project).filter(Project.id == project_id).first()
    project_tasks = my_project.tasks
    return render_template('projects/project.html', project=my_project, tasks=project_tasks)


@projects.route('/project/<int:project_id>/delete', methods=['POST'])
def delete_project(project_id):
    my_project = db_session.query(Project).get(project_id)
    if my_project:
        db_session.delete(my_project)
        db_session.commit()
        flash('Your project has been deleted!', 'success')
        return redirect(url_for('main.home'))
    flash('Project deletion failed!', 'danger')
    return redirect(url_for('main.home'))

taskler/subtypes/routes.py
from flask import Blueprint, flash, redirect, url_for, render_template
from taskler.subtypes.forms import SubtypeForm
from taskler.db import db_session
from taskler.models import Subtype


subtypes = Blueprint('subtypes', __name__)


@subtypes.route('/subtype/new', methods=['GET', 'POST'])
def new_subtype():
    form = SubtypeForm()
    my_subtypes = db_session.query(Subtype).all()
    if form.validate_on_submit():
        my_subtype = Subtype(type=form.type.data)
        db_session.add(my_subtype)
        db_session.commit()
        flash('You have successfully created a subtype. You can apply it to a task', 'success')
        return redirect(url_for('subtypes.all_subtypes'))
    return render_template('subtypes/create_subtype.html', form=form, subtypes=my_subtypes)


@subtypes.route('/subtype/all')
def all_subtypes():
    my_subtypes = db_session.query(Subtype).all()
    return render_template('subtypes/all_subtypes.html', subtypes=my_subtypes)


@subtypes.route('/subtype/<int:subtype_id>/delete', methods=['POST'])
def delete_subtype(subtype_id):
    my_subtype = db_session.query(Subtype).get(subtype_id)
    if my_subtype:
        db_session.delete(my_subtype)
        db_session.commit()
        flash('Your subtype has been deleted!', 'success')
        return redirect(url_for('subtypes.all_subtypes'))
    flash('Subtype deletion failed!', 'danger')
    return redirect(url_for('subtypes.all_subtypes'))

taskler/tasks/routes.py
from flask import Blueprint, flash, redirect, url_for, render_template, request
from taskler.models import Task
from taskler.tasks.forms import TaskForm
from taskler.db import db_session
from taskler.models import Project, Subtype
from taskler.utils import local_to_utc


tasks = Blueprint('tasks', __name__)


@tasks.route('/task/new', methods=['GET', 'POST'])
def new_task():
    form = TaskForm()
    if form.validate_on_submit():
        project_id = db_session.query(Project).filter(Project.title == form.project_name.data).first().id
        my_task = Task(title=form.title.data,
                       description=form.description.data,
                       date_due=local_to_utc(form.date_due.data),
                       start_date=local_to_utc(form.start_date.data),
                       status=form.status.data,
                       project_id=project_id)
        task_subtypes = []
        for subtype in form.subtypes.data:
            task_subtypes.append(db_session.query(Subtype).filter(Subtype.type == subtype).first())
        my_task.subtypes = task_subtypes
        db_session.add(my_task)
        db_session.commit()
        flash('Your task has been created!', 'success')
        return redirect(url_for('tasks.task', task_id=my_task.id))
    return render_template('tasks/create_task.html', form=form)


# Don't think this route is necessary any more
# @tasks.route('/task/all')
# def all_tasks():
#     my_tasks = db_session.query(Task).all()
#     return render_template('tasks/all_tasks.html', tasks=my_tasks)


@tasks.route('/task/<int:task_id>')
def task(task_id):
    my_task = db_session.query(Task).get(task_id)
    return render_template('tasks/task.html', task=my_task)


@tasks.route('/task/<int:task_id>/update', methods=['GET', 'POST'])
def update_task(task_id):
    my_task = db_session.query(Task).get(task_id)
    form = TaskForm()
    if form.validate_on_submit():
        my_task.title = form.title.data
        my_task.description = form.description.data
        my_task.date_due = form.date_due.data
        my_task.status = form.status.data
        # my_task.subtypes = form.subtypes.data
        db_session.add(my_task)
        db_session.commit()
        flash('Your task has successfully updated', 'success')
        return redirect(url_for('tasks.task', task_id=my_task.id))
    elif request.method == 'GET':
        form.title.data = my_task.title
        form.description.data = my_task.description
        form.date_due.data = my_task.date_due
        form.project_name.data = my_task.project.title
        form.status.data = my_task.status
        # form.subtypes.data = my_task.subtypes
    return render_template('tasks/create_task.html', title='Update Task', form=form)


@tasks.route('/task/<int:task_id>/delete', methods=['POST'])
def delete_task(task_id):
    my_task = db_session.query(Task).get(task_id)
    if my_task:
        project_id = my_task.project.id
        db_session.delete(my_task)
        db_session.commit()
        flash('Your task has been deleted!', 'success')
        return redirect(url_for('projects.project', project_id=project_id))
    flash('Task deletion failed', 'danger')
    return render_template(url_for('main.home'))

taskler/templates/partials/create_project_form.html
{% if title %}
  <h1>{{ title }}</h1>
{% endif %}
<div>
  <form method="POST" action="">
    {{ form.csrf_token }}
    <fieldset>
      <div>
        {{ form.title.label }}
        {% if form.title.errors %}
          {{ form.title }}
          {% for error in form.title.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.title }}
        {% endif %}
      </div>
      <div>
        {{ form.description.label }}
        {% if form.description.errors %}
          {{ form.description }}
          {% for error in form.description.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.description }}
        {% endif %}
      </div>
      <div>
        {{ form.start_date.label }}
        {% if form.start_date.errors %}
          {{ form.start_date }}
          {% for error in form.start_date.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.start_date }}
        {% endif %}
      </div>
      <div>
        {{ form.end_date.label }}
        {% if form.end_date.errors %}
          {{ form.end_date }}
          {% for error in form.end_date.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.end_date }}
        {% endif %}
      </div>
      <div>
        {{ form.status.label }}
        {% if form.status.errors %}
          {{ form.status }}
          {% for error in form.status.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.status }}
        {% endif %}
      </div>
    </fieldset>
    <div>
      {{ form.submit }}
    </div>
  </form>
</div>

taskler/templates/partials/create_task_form.html
{% if title %}
  <h1>{{ title }}</h1>
{% endif %}
<div>
  <h2>Create New Task</h2>
  <form method="POST" action="">
    {{ form.csrf_token }}
    <fieldset>
      <div>
        {{ form.title.label }}
        {% if form.title.errors %}
          {{ form.title }}
          {% for error in form.title.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.title }}
        {% endif %}
      </div>
      <div>
        {{ form.description.label }}
        {% if form.description.errors %}
          {{ form.description }}
          {% for error in form.description.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.description }}
        {% endif %}
      </div>
      <div>
        {{ form.start_date.label }}
        {% if form.start_date.errors %}
          {{ form.start_date }}
          {% for error in form.start_date.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.start_date }}
        {% endif %}
      </div>
      <div>
        {{ form.date_due.label }}
        {% if form.date_due.errors %}
          {{ form.date_due }}
          {% for error in form.date_due.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.date_due }}
        {% endif %}
      </div>
      {% if not project %}
        <div>
          {{ form.project_name.label }}
          {% if form.project_name.errors %}
            {{ form.project_name }}
            {% for error in form.project_name.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          {% else %}
            {{ form.project_name }}
          {% endif %}
        </div>
      {% endif %}
      <div>
        {{ form.status.label }}
        {% if form.status.errors %}
          {{ form.status }}
          {% for error in form.status.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.status }}
        {% endif %}
      </div>
      <div>
        {{ form.subtypes.label }}
        {% if form.subtypes.errors %}
          {{ form.subtypes }}
          {% for error in form.subtypes.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% else %}
          {{ form.subtypes }}
        {% endif %}
      </div>
    </fieldset>
    <div>
      {{ form.submit }}
    </div>
  </form>
</div>

taskler/templates/partials/project_card.html
<div id="project-card">
  <div class="card-title">{{ project.title }}</div>
  <div class="card-desc">Description: {{ project.description }}</div>
  {% if project.start_date %}
    <div class="card-child">Start Date: {{ moment(project.start_date).format('MMMM Do YYYY h:mm a') }}</div>
  {% else %}
    <div class="card-child">No Start Date</div>
  {% endif %}
  {% if project.end_date %}
    <div class="card-child">End Date: {{ moment(project.end_date).format('MMMM Do YYYY h:mm a') }}</div>
  {% else %}
    <div class="card-child">No End Date</div>
  {% endif %}
  <div class="card-child">Current Status: {{ project.status }}</div>
</div>
<div>
  <div class="project-status">Created</div>
  {% for task in project.tasks %}
    {% if task.status == 'Created' %}
      <div class="task-card">
        <a href="{{ url_for('tasks.task', task_id=task.id) }}">{{ task.title }}</a>
        <div>{{ task.description }}</div>
        {% if task.date_due %}
          <div>Due: {{ moment(task.date_due).format('MMMM Do YYYY h:mm a') }}</div>
        {% else %}
          <div>No Due Date</div>
        {% endif %}
        <a class="btn btn-info btn-sm" href="{{ url_for('tasks.update_task', task_id=task.id) }}">+</a>
        <form action="{{ url_for('tasks.delete_task', task_id=task.id) }}" method="POST">
          <input class="btn btn-danger btn-sm" type="submit" value="x">
        </form>
      </div>
    {% endif %}
  {% endfor %}
  <div class="project-status">In Work</div>
  {% for task in project.tasks %}
    {% if task.status == 'In Work' %}
      <div class="task-card">
        <a href="{{ url_for('tasks.task', task_id=task.id) }}">{{ task.title }}</a>
        <div>{{ task.description }}</div>
        {% if task.date_due %}
          <div>Due: {{ moment(task.date_due).format('MMMM Do YYYY') }}</div>
        {% else %}
          <div>No Due Date</div>
        {%  endif %}
        <a class="btn btn-info btn-sm" href="{{ url_for('tasks.update_task', task_id=task.id) }}">+</a>
        <form action="{{ url_for('tasks.delete_task', task_id=task.id) }}" method="POST">
          <input class="btn btn-danger btn-sm" type="submit" value="x">
        </form>
      </div>
    {% endif %}
  {% endfor %}
  <div class="project-status">Complete</div>
  {% for task in project.tasks %}
    {% if task.status == 'Complete' %}
      <div class="task-card">
        <a href="{{ url_for('tasks.task', task_id=task.id) }}">{{ task.title }}</a>
        <div>{{ task.description }}</div>
        {% if task.date_due %}
          <div>Due: {{ task.date_due.date() }}</div>
        {% else %}
          <div>No Due Date</div>
        {% endif %}
        <a class="btn btn-info btn-sm" href="{{ url_for('tasks.update_task', task_id=task.id) }}">+</a>
        <form action="{{ url_for('tasks.delete_task', task_id=task.id) }}" method="POST">
          <input class="btn btn-danger btn-sm" type="submit" value="x">
        </form>
      </div>
    {% endif %}
  {% endfor %}
  <div>
    {% if not project.tasks %}
      <div class="task-card">This project currently has no associated tasks,
        <a href="{{ url_for('projects.new_project_task', project_id=project.id) }}">Create One Here!</a>
      </div>
    {% endif %}
  </div>
</div>

taskler/templates/partials/subtypes_card.html
<div class="subtype-card">
  <div class="card-title">All Subtypes</div>
  {% for subtype in subtypes %}
    <div class="card-child">
      {{ subtype.type }}
      <form action="{{ url_for('subtypes.delete_subtype', subtype_id=subtype.id) }}" method="POST">
        <input class="btn btn-danger btn-sm" type="submit" value="x">
      </form>
    </div>
  {% endfor %}
</div>