taskler/projects/forms.py
import datetime
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField, SelectMultipleField
from wtforms.validators import DataRequired, Length, Optional
from wtforms.fields.html5 import DateTimeLocalField


class ProjectForm(FlaskForm):
    title = StringField('Title',
                        validators=[DataRequired(), Length(max=50)],
                        render_kw={'placeholder': 'Enter title...'})
    description = TextAreaField('Description',
                                validators=[DataRequired(), Length(max=300)],
                                render_kw={'placeholder': 'Enter description...'})
    start_date = DateTimeLocalField('Start Date',
                                    default=datetime.datetime.now(),
                                    format='%Y-%m-%dT%H:%M',
                                    validators=[Optional()])
    end_date = DateTimeLocalField('End Date',
                                  format='%Y-%m-%dT%H:%M',
                                  validators=[Optional()])
    status = SelectField('Status Upon Creation',
                         choices=['Created', 'In Work', 'Complete', 'On Hold'],
                         # need to export these options somewhere
                         validators=[DataRequired()])
    submit = SubmitField('Create Project')

taskler/projects/routes.py
from flask import render_template, Blueprint, flash, redirect, url_for, request
from taskler.models import Project, Task, Subtype
from taskler.db import db_session
from taskler.projects.forms import ProjectForm
from taskler.tasks.forms import TaskForm
from taskler.utils import local_to_utc


projects = Blueprint('projects', __name__)


@projects.route('/project/new', methods=['GET', 'POST'])
def new_project():
    form = ProjectForm()
    if form.validate_on_submit():
        my_project = Project(title=form.title.data,
                             description=form.description.data,
                             start_date=local_to_utc(form.start_date.data),
                             end_date=local_to_utc(form.end_date.data),
                             status=form.status.data)
        db_session.add(my_project)
        db_session.commit()
        flash('Your project has been created!', 'success')
        return redirect(url_for('projects.project', project_id=my_project.id))
    return render_template('projects/create_project.html', form=form)


@projects.route('/project/<int:project_id>/update', methods=['GET', 'POST'])
def update_project(project_id):
    form = ProjectForm()
    my_project = db_session.query(Project).filter(Project.id == project_id).first()
    if form.validate_on_submit():
        my_project.start_date = form.start_date.data
        my_project.end_date = form.end_date.data
        my_project.title = form.title.data
        my_project.description = form.description.data
        db_session.add(my_project)
        db_session.commit()
        return redirect(url_for('projects.project', project_id=my_project.id))
    elif request.method == 'GET':
        form.start_date.data = my_project.start_date
        form.end_date.data = my_project.end_date
        form.title.data = my_project.title
        form.description.data = my_project.description
    return render_template('projects/update_project.html', form=form)


@projects.route('/project/<int:project_id>/new-task', methods=['GET', 'POST'])
def new_project_task(project_id):
    form = TaskForm()
    my_project = db_session.query(Project).get(project_id)
    if form.validate_on_submit():
        my_task = Task(title=form.title.data,
                       description=form.description.data,
                       date_due=local_to_utc(form.date_due.data),
                       start_date=local_to_utc(form.start_date.data),
                       project_id=my_project.id,
                       status=form.status.data)
        task_subtypes = []
        for subtype in form.subtypes.data:
            task_subtypes.append(db_session.query(Subtype).filter(Subtype.type == subtype).first())
        my_task.subtypes = task_subtypes
        db_session.add(my_task)
        db_session.commit()
        flash('Your task has been created!', 'success')
        return redirect(url_for('projects.project', project_id=my_project.id))
    return render_template('projects/create_project_task.html', form=form, project=my_project)


@projects.route('/project/<int:project_id>')
def project(project_id):
    my_project = db_session.query(Project).filter(Project.id == project_id).first()
    project_tasks = my_project.tasks
    return render_template('projects/project.html', project=my_project, tasks=project_tasks)


@projects.route('/project/<int:project_id>/delete', methods=['POST'])
def delete_project(project_id):
    my_project = db_session.query(Project).get(project_id)
    if my_project:
        db_session.delete(my_project)
        db_session.commit()
        flash('Your project has been deleted!', 'success')
        return redirect(url_for('main.home'))
    flash('Project deletion failed!', 'danger')
    return redirect(url_for('main.home'))

taskler/templates/projects/create_project.html
{% extends "base.html" %}
{% block content %}
  {% if title %}
    <h1>{{ title }}</h1>
  {% endif %}
  <div>
    <form method="POST" action="">
      {{ form.csrf_token }}
      <fieldset>
        <div>
          {{ form.title.label }}
          {% if form.title.errors %}
            {{ form.title }}
            {% for error in form.title.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          {% else %}
            {{ form.title }}
          {% endif %}
        </div>
        <div>
          {{ form.description.label }}
          {% if form.description.errors %}
            {{ form.description }}
            {% for error in form.description.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          {% else %}
            {{ form.description }}
          {% endif %}
        </div>
        <div>
          {{ form.start_date.label }}
          {% if form.start_date.errors %}
            {{ form.start_date }}
            {% for error in form.start_date.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          {% else %}
            {{ form.start_date }}
          {% endif %}
        </div>
        <div>
          {{ form.end_date.label }}
          {% if form.end_date.errors %}
            {{ form.end_date }}
            {% for error in form.end_date.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          {% else %}
            {{ form.end_date }}
          {% endif %}
        </div>
        <div>
          {{ form.status.label }}
          {% if form.status.errors %}
            {{ form.status }}
            {% for error in form.status.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          {% else %}
            {{ form.status }}
          {% endif %}
        </div>
      </fieldset>
      <div>
        {{ form.submit }}
      </div>
    </form>
  </div>
{% endblock content %}

taskler/templates/projects/create_project_task.html
{% extends "base.html" %}
{%  block content %}
  {% include "partials/project_card.html" %}
  {% include "partials/create_task_form.html" %}
{% endblock %}

taskler/templates/projects/project.html
{% extends "base.html" %}
{% block content %}
  {% include "partials/project_card.html" %}
  <div>
    <a class="btn btn-info" href="{{ url_for('projects.update_project', project_id=project.id) }}">Update</a>
    <a class="btn btn-outline-info" href="{{ url_for('projects.new_project_task', project_id=project.id) }}">New Task</a>
    <form action="{{ url_for('projects.delete_project', project_id=project.id) }}" method="POST">
      <input class="btn btn-danger" type="submit" value="Delete Project">
    </form>
  </div>
{% endblock content %}

taskler/templates/projects/update_project.html
{% extends "base.html" %}
{% block content %}
  {% include "partials/create_project_form.html" %}
{% endblock content %}